### ISSUE TITLE
Use mtime instead of ctime

### ISSUE THREAD

**Issue by 5slight** [shonny-ua/gulp-rev-outdated#11]
I was finding most of the time it was keeping older files rather than new files. Was a little erratic though. In my case, this was because it basing latest files on ctime rather than mtime. ctime is change time and will get updated when any meta data or contents of a file changes. mtime only changes when the contents changes. 

Surely we should only care about the contents being changed because a new file is always going to be created by rev when the contents change and that should superseded old files regardless of meta data.

I don't know why my build is breaking with ctime it seems strange to me thats getting updated on every build but regardless I think mtime is the more correct and stable metric to use for this purpose.

**Comment by shonny-ua** [comment]
use version 1.0.1
